language: cpp

compiler: gcc

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode10.2
  exclude:
    - compiler: gcc    # travis bug: https://github.com/travis-ci/travis-ci/issues/4681

before_install:
  # travis bug: https://github.com/travis-ci/travis-ci/issues/6048
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then
      sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 3B4FE6ACC0B21F32 40976EAF437D05B5;
      sudo apt-get update;
      sudo apt-get install -q -y xorg-dev libfontconfig1-dev;
    fi

script:
  - cmake . && cmake --build .
  
notifications:
  email: false
